// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order_refund_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OrderRefundModel _$OrderRefundModelFromJson(Map<String, dynamic> json) =>
    OrderRefundModel(
      viewRefunds: (json['data'] as List<dynamic>?)
          ?.map((e) => ViewRefunds.fromJson(e as Map<String, dynamic>))
          .toList(),
    )
      ..success = json['success'] as String?
      ..status = json['status'] as bool?
      ..message = json['message'] as String?
      ..cartCount = json['cartCount'] as int?
      ..error = json['error'];

Map<String, dynamic> _$OrderRefundModelToJson(OrderRefundModel instance) =>
    <String, dynamic>{
      'success': instance.success,
      'status': instance.status,
      'message': instance.message,
      'cartCount': instance.cartCount,
      'error': instance.error,
      'data': instance.viewRefunds,
    };

ViewRefunds _$ViewRefundsFromJson(Map<String, dynamic> json) => ViewRefunds(
      id: json['id'] as int?,
      incrementId: json['incrementId'],
      state: json['state'] as String?,
      emailSent: json['emailSent'] as int?,
      totalQty: json['totalQty'] as int?,
      baseCurrencyCode: json['baseCurrencyCode'] as String?,
      channelCurrencyCode: json['channelCurrencyCode'] as String?,
      orderCurrencyCode: json['orderCurrencyCode'] as String?,
      adjustmentRefund: json['adjustmentRefund'] as int?,
      baseAdjustmentRefund: json['baseAdjustmentRefund'] as int?,
      adjustmentFee: json['adjustmentFee'] as int?,
      baseAdjustmentFee: json['baseAdjustmentFee'] as int?,
      subTotal: json['subTotal'] as int?,
      baseSubTotal: json['baseSubTotal'] as int?,
      grandTotal: json['grandTotal'] as int?,
      baseGrandTotal: json['baseGrandTotal'] as int?,
      shippingAmount: json['shippingAmount'] as int?,
      baseShippingAmount: json['baseShippingAmount'] as int?,
      taxAmount: json['taxAmount'] as int?,
      baseTaxAmount: json['baseTaxAmount'] as int?,
      discountPercent: json['discountPercent'] as int?,
      discountAmount: json['discountAmount'] as int?,
      baseDiscountAmount: json['baseDiscountAmount'] as int?,
      orderId: json['orderId'] as int?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      items: (json['items'] as List<dynamic>?)
          ?.map((e) => RefundItems.fromJson(e as Map<String, dynamic>))
          .toList(),
      order: json['order'] == null
          ? null
          : Order.fromJson(json['order'] as Map<String, dynamic>),
      formattedPrice: json['formattedPrice'] == null
          ? null
          : FormattedPrice.fromJson(
              json['formattedPrice'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$ViewRefundsToJson(ViewRefunds instance) =>
    <String, dynamic>{
      'id': instance.id,
      'incrementId': instance.incrementId,
      'state': instance.state,
      'emailSent': instance.emailSent,
      'totalQty': instance.totalQty,
      'baseCurrencyCode': instance.baseCurrencyCode,
      'channelCurrencyCode': instance.channelCurrencyCode,
      'orderCurrencyCode': instance.orderCurrencyCode,
      'adjustmentRefund': instance.adjustmentRefund,
      'baseAdjustmentRefund': instance.baseAdjustmentRefund,
      'adjustmentFee': instance.adjustmentFee,
      'baseAdjustmentFee': instance.baseAdjustmentFee,
      'subTotal': instance.subTotal,
      'baseSubTotal': instance.baseSubTotal,
      'grandTotal': instance.grandTotal,
      'baseGrandTotal': instance.baseGrandTotal,
      'shippingAmount': instance.shippingAmount,
      'baseShippingAmount': instance.baseShippingAmount,
      'taxAmount': instance.taxAmount,
      'baseTaxAmount': instance.baseTaxAmount,
      'discountPercent': instance.discountPercent,
      'discountAmount': instance.discountAmount,
      'baseDiscountAmount': instance.baseDiscountAmount,
      'orderId': instance.orderId,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'formattedPrice': instance.formattedPrice,
      'items': instance.items,
      'order': instance.order,
    };

RefundItems _$RefundItemsFromJson(Map<String, dynamic> json) => RefundItems(
      id: json['id'] as int?,
      name: json['name'] as String?,
      description: json['description'],
      sku: json['sku'] as String?,
      qty: json['qty'] as int?,
      price: json['price'] as int?,
      basePrice: json['basePrice'] as int?,
      total: json['total'] as int?,
      baseTotal: json['baseTotal'] as int?,
      taxAmount: json['taxAmount'] as int?,
      baseTaxAmount: json['baseTaxAmount'] as int?,
      discountPercent: json['discountPercent'] as int?,
      discountAmount: json['discountAmount'] as int?,
      baseDiscountAmount: json['baseDiscountAmount'] as int?,
      productId: json['productId'] as int?,
      productType: json['productType'] as String?,
      orderItemId: json['orderItemId'] as int?,
      refundId: json['refundId'] as int?,
      parentId: json['parentId'],
      additional: json['additional'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      product: json['product'] == null
          ? null
          : Product.fromJson(json['product'] as Map<String, dynamic>),
      formattedPrice: json['formattedPrice'] == null
          ? null
          : FormattedPrice.fromJson(
              json['formattedPrice'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$RefundItemsToJson(RefundItems instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'description': instance.description,
      'sku': instance.sku,
      'qty': instance.qty,
      'price': instance.price,
      'basePrice': instance.basePrice,
      'total': instance.total,
      'baseTotal': instance.baseTotal,
      'taxAmount': instance.taxAmount,
      'baseTaxAmount': instance.baseTaxAmount,
      'discountPercent': instance.discountPercent,
      'discountAmount': instance.discountAmount,
      'baseDiscountAmount': instance.baseDiscountAmount,
      'productId': instance.productId,
      'productType': instance.productType,
      'orderItemId': instance.orderItemId,
      'refundId': instance.refundId,
      'parentId': instance.parentId,
      'additional': instance.additional,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'product': instance.product,
      'formattedPrice': instance.formattedPrice,
    };

Order _$OrderFromJson(Map<String, dynamic> json) => Order(
      id: json['id'] as int?,
      incrementId: json['incrementId'] as String?,
      status: json['status'] as String?,
      channelName: json['channelName'] as String?,
      isGuest: json['isGuest'] as int?,
      customerEmail: json['customerEmail'] as String?,
      customerFirstName: json['customerFirstName'] as String?,
      customerLastName: json['customerLastName'] as String?,
      customerCompanyName: json['customerCompanyName'],
      customerVatId: json['customerVatId'],
      shippingMethod: json['shippingMethod'] as String?,
      shippingTitle: json['shippingTitle'] as String?,
      shippingDescription: json['shippingDescription'] as String?,
      couponCode: json['couponCode'],
      isGift: json['isGift'] as int?,
      totalItemCount: json['totalItemCount'] as int?,
      totalQtyOrdered: json['totalQtyOrdered'] as int?,
      baseCurrencyCode: json['baseCurrencyCode'] as String?,
      channelCurrencyCode: json['channelCurrencyCode'] as String?,
      orderCurrencyCode: json['orderCurrencyCode'] as String?,
      grandTotal: json['grandTotal'] as int?,
      baseGrandTotal: json['baseGrandTotal'] as int?,
      grandTotalInvoiced: json['grandTotalInvoiced'] as int?,
      baseGrandTotalInvoiced: json['baseGrandTotalInvoiced'] as int?,
      grandTotalRefunded: json['grandTotalRefunded'] as int?,
      baseGrandTotalRefunded: json['baseGrandTotalRefunded'] as int?,
      subTotal: json['subTotal'] as int?,
      baseSubTotal: json['baseSubTotal'] as int?,
      subTotalInvoiced: json['subTotalInvoiced'] as int?,
      baseSubTotalInvoiced: json['baseSubTotalInvoiced'] as int?,
      subTotalRefunded: json['subTotalRefunded'] as int?,
      baseSubTotalRefunded: json['baseSubTotalRefunded'] as int?,
      discountPercent: json['discountPercent'] as int?,
      discountAmount: json['discountAmount'] as int?,
      baseDiscountAmount: json['baseDiscountAmount'] as int?,
      discountInvoiced: json['discountInvoiced'] as int?,
      baseDiscountInvoiced: json['baseDiscountInvoiced'] as int?,
      discountRefunded: json['discountRefunded'] as int?,
      baseDiscountRefunded: json['baseDiscountRefunded'] as int?,
      taxAmount: json['taxAmount'] as int?,
      baseTaxAmount: json['baseTaxAmount'] as int?,
      taxAmountInvoiced: json['taxAmountInvoiced'] as int?,
      baseTaxAmountInvoiced: json['baseTaxAmountInvoiced'] as int?,
      taxAmountRefunded: json['taxAmountRefunded'] as int?,
      baseTaxAmountRefunded: json['baseTaxAmountRefunded'] as int?,
      shippingAmount: json['shippingAmount'] as int?,
      baseShippingAmount: json['baseShippingAmount'] as int?,
      shippingInvoiced: json['shippingInvoiced'] as int?,
      baseShippingInvoiced: json['baseShippingInvoiced'] as int?,
      shippingRefunded: json['shippingRefunded'] as int?,
      baseShippingRefunded: json['baseShippingRefunded'] as int?,
      customerId: json['customerId'] as int?,
      customerType: json['customerType'] as String?,
      channelId: json['channelId'] as int?,
      channelType: json['channelType'] as String?,
      cartId: json['cartId'] as String?,
      appliedCartRuleIds: json['appliedCartRuleIds'] as String?,
      shippingDiscountAmount: json['shippingDiscountAmount'] as int?,
      baseShippingDiscountAmount: json['baseShippingDiscountAmount'] as int?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
    );

Map<String, dynamic> _$OrderToJson(Order instance) => <String, dynamic>{
      'id': instance.id,
      'incrementId': instance.incrementId,
      'status': instance.status,
      'channelName': instance.channelName,
      'isGuest': instance.isGuest,
      'customerEmail': instance.customerEmail,
      'customerFirstName': instance.customerFirstName,
      'customerLastName': instance.customerLastName,
      'customerCompanyName': instance.customerCompanyName,
      'customerVatId': instance.customerVatId,
      'shippingMethod': instance.shippingMethod,
      'shippingTitle': instance.shippingTitle,
      'shippingDescription': instance.shippingDescription,
      'couponCode': instance.couponCode,
      'isGift': instance.isGift,
      'totalItemCount': instance.totalItemCount,
      'totalQtyOrdered': instance.totalQtyOrdered,
      'baseCurrencyCode': instance.baseCurrencyCode,
      'channelCurrencyCode': instance.channelCurrencyCode,
      'orderCurrencyCode': instance.orderCurrencyCode,
      'grandTotal': instance.grandTotal,
      'baseGrandTotal': instance.baseGrandTotal,
      'grandTotalInvoiced': instance.grandTotalInvoiced,
      'baseGrandTotalInvoiced': instance.baseGrandTotalInvoiced,
      'grandTotalRefunded': instance.grandTotalRefunded,
      'baseGrandTotalRefunded': instance.baseGrandTotalRefunded,
      'subTotal': instance.subTotal,
      'baseSubTotal': instance.baseSubTotal,
      'subTotalInvoiced': instance.subTotalInvoiced,
      'baseSubTotalInvoiced': instance.baseSubTotalInvoiced,
      'subTotalRefunded': instance.subTotalRefunded,
      'baseSubTotalRefunded': instance.baseSubTotalRefunded,
      'discountPercent': instance.discountPercent,
      'discountAmount': instance.discountAmount,
      'baseDiscountAmount': instance.baseDiscountAmount,
      'discountInvoiced': instance.discountInvoiced,
      'baseDiscountInvoiced': instance.baseDiscountInvoiced,
      'discountRefunded': instance.discountRefunded,
      'baseDiscountRefunded': instance.baseDiscountRefunded,
      'taxAmount': instance.taxAmount,
      'baseTaxAmount': instance.baseTaxAmount,
      'taxAmountInvoiced': instance.taxAmountInvoiced,
      'baseTaxAmountInvoiced': instance.baseTaxAmountInvoiced,
      'taxAmountRefunded': instance.taxAmountRefunded,
      'baseTaxAmountRefunded': instance.baseTaxAmountRefunded,
      'shippingAmount': instance.shippingAmount,
      'baseShippingAmount': instance.baseShippingAmount,
      'shippingInvoiced': instance.shippingInvoiced,
      'baseShippingInvoiced': instance.baseShippingInvoiced,
      'shippingRefunded': instance.shippingRefunded,
      'baseShippingRefunded': instance.baseShippingRefunded,
      'customerId': instance.customerId,
      'customerType': instance.customerType,
      'channelId': instance.channelId,
      'channelType': instance.channelType,
      'cartId': instance.cartId,
      'appliedCartRuleIds': instance.appliedCartRuleIds,
      'shippingDiscountAmount': instance.shippingDiscountAmount,
      'baseShippingDiscountAmount': instance.baseShippingDiscountAmount,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
    };
